In [125]:
import pandas as pd 
df = pd.read_csv("Task1_combined_data.csv")
df.head()

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,books_borrowed,genre,pages,publication_year,publisher
0,9263.0,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,16,Mystery,338,2015.0,Delta House
1,9340.0,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,14,Science,294,2021.0,Oasis Books
2,9231.0,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,5,Historical,276,2018.0,Oasis Books
3,9129.0,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,6,Science,294,2021.0,Oasis Books
4,9370.0,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27,10,Historical,117,2016.0,Nile Press

In [126]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   checkout_id        391 non-null    float64
 1   member_id          412 non-null    int64
 2   book_id            412 non-null    int64
 3   checkout_date      412 non-null    str
 4   return_date        326 non-null    str
 5   first_name         412 non-null    str
 6   last_name          412 non-null    str
 7   grade              376 non-null    float64
 8   neighborhood       412 non-null    str
 9   membership_status  412 non-null    str
 10  join_date          406 non-null    str
 11  books_borrowed     412 non-null    int64
 12  genre              412 non-null    str
 13  pages              412 non-null    int64
 14  publication_year   377 non-null    float64
 15  publisher          412 non-null    str
dtypes: float64(3), int64(4), str(9)
memory usage: 51.6 KB

In [127]:
df["checkout_date"] = pd.to_datetime(df["checkout_date"])
df["return_date"] = pd.to_datetime(df["return_date"])
df["join_date"] = pd.to_datetime(df["join_date"])
df["grade"] = df["grade"].astype("Int64")
df["checkout_id"] = df["checkout_id"].astype("Int64")
df["publication_year"] = df["publication_year"].astype("Int64")

df.dtypes

checkout_id                   Int64
member_id                     int64
book_id                       int64
checkout_date        datetime64[us]
return_date          datetime64[us]
first_name                      str
last_name                       str
grade                         Int64
neighborhood                    str
membership_status               str
join_date            datetime64[us]
books_borrowed                int64
genre                           str
pages                         int64
publication_year              Int64
publisher                       str
dtype: object

In [128]:
df.duplicated().sum()

np.int64(8)

In [129]:
duplicates = df[df.duplicated(keep=False)]

duplicates

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,books_borrowed,genre,pages,publication_year,publisher
69,9296,1065,501,2024-12-15,2025-01-11,Adam,Fahmy,6,Zamalek,Active,2025-07-12,17,Adventure,128,2017,Nile Press
73,9280,1054,517,2024-09-06,2024-09-15,Retaj,Fahmy,6,Heliopolis,Inactive,2024-03-21,6,Mystery,338,2015,Delta House
113,9052,1019,501,2024-06-20,2024-06-29,Mostafa,Wahba,6,Maadi,Inactive,2024-07-20,3,Adventure,128,2017,Nile Press
116,9194,1024,513,2024-09-17,2024-10-09,Youssef,Hegazy,8,Nasr City,inactive,2024-01-04,17,Science,294,2021,Oasis Books
121,9193,1034,519,2024-09-15,2024-10-01,Aya,Wahba,9,Nasr City,Active,2025-01-22,25,Friendship,157,2014,Nile Press
225,9296,1065,501,2024-12-15,2025-01-11,Adam,Fahmy,6,Zamalek,Active,2025-07-12,17,Adventure,128,2017,Nile Press
244,9334,1065,507,2025-12-20,2026-01-05,Adam,Fahmy,6,Zamalek,Active,2025-07-12,17,Science,160,2024,Nile Press
246,9180,1034,529,2024-07-27,2024-08-02,Aya,Wahba,9,Nasr City,Active,2025-01-22,25,Mystery,298,<NA>,Cairo Young Readers
278,9180,1034,529,2024-07-27,2024-08-02,Aya,Wahba,9,Nasr City,Active,2025-01-22,25,Mystery,298,<NA>,Cairo Young Readers
301,9334,1065,507,2025-12-20,2026-01-05,Adam,Fahmy,6,Zamalek,Active,2025-07-12,17,Science,160,2024,Nile Press
330,9246,1044,529,2025-06-25,2025-07-04,Sherif,Saleh,7,Heliopolis,active,2024-02-19,21,Mystery,298,<NA>,Cairo Young Readers
333,9194,1024,513,2024-09-17,2024-10-09,Youssef,Hegazy,8,Nasr City,inactive,2024-01-04,17,Science,294,2021,Oasis Books
357,9052,1019,501,2024-06-20,2024-06-29,Mostafa,Wahba,6,Maadi,Inactive,2024-07-20,3,Adventure,128,2017,Nile Press
375,9193,1034,519,2024-09-15,2024-10-01,Aya,Wahba,9,Nasr City,Active,2025-01-22,25,Friendship,157,2014,Nile Press
378,9280,1054,517,2024-09-06,2024-09-15,Retaj,Fahmy,6,Heliopolis,Inactive,2024-03-21,6,Mystery,338,2015,Delta House
390,9246,1044,529,2025-06-25,2025-07-04,Sherif,Saleh,7,Heliopolis,active,2024-02-19,21,Mystery,298,<NA>,Cairo Young Readers

In [130]:
df = df.drop_duplicates(keep='first')

df.duplicated().sum()

np.int64(0)

In [131]:
df.isna().sum()

checkout_id          21
member_id             0
book_id               0
checkout_date         0
return_date          86
first_name            0
last_name             0
grade                36
neighborhood          0
membership_status     0
join_date             6
books_borrowed        0
genre                 0
pages                 0
publication_year     33
publisher             0
dtype: int64

In [132]:
missing_percentage = (df.isna().mean() * 100).round(2)

missing_percentage[missing_percentage > 0]

checkout_id          5.20
return_date         21.29
grade                8.91
join_date            1.49
publication_year     8.17
dtype: float64

In [133]:
# chechout_id 
max_id = df["checkout_id"].max()

missing_count = df["checkout_id"].isna().sum()

df.loc[df["checkout_id"].isna(), "checkout_id"] = range(
    max_id + 1,
    max_id + 1 + missing_count )

print (df["checkout_id"].isna().sum())

0

In [134]:
# return_data 

# I will leave the missing values in the return_date column as they are because a missing return date
# does not necessarily indicate an error in the data. It can mean that the book has not been returned yet,
# so there is no return date to record. Therefore, filling these missing values with an estimated or
# arbitrary date could make the data inaccurate and misleading.

In [135]:
# grade 

df["grade"] = df["grade"].fillna(df["grade"].mode()[0])

print (df["grade"].isna().sum())

0

In [136]:
# join_date

df["join_date"] = df["join_date"].fillna(df["join_date"].mode()[0])

print (df["join_date"].isna().sum())

0

In [137]:
# publication_year

df = df.dropna(subset=["publication_year"])

print (df["publication_year"].isna().sum())

# I decided to remove the rows with missing values in the publication_year column because I do not have
# a reliable source to determine the correct publication year for these books. Since the number of missing
# values is small, removing these rows is preferable to guessing or filling in incorrect information.
# This helps maintain the accuracy and reliability of the dataset.

0

In [138]:
missing_percentage = (df.isna().mean() * 100).round(2)

missing_percentage[missing_percentage > 0]

return_date    21.83
dtype: float64

In [139]:
df.dtypes

checkout_id                   Int64
member_id                     int64
book_id                       int64
checkout_date        datetime64[us]
return_date          datetime64[us]
first_name                      str
last_name                       str
grade                         Int64
neighborhood                    str
membership_status               str
join_date            datetime64[us]
books_borrowed                int64
genre                           str
pages                         int64
publication_year              Int64
publisher                       str
dtype: object

In [140]:
df["first_name"] = df["first_name"].str.strip().str.title()
df["first_name"].unique()

<StringArray>
[   'Sara',    'Seif',    'Adam',    'Nada',    'Rana',    'Nour',   'Ahmed',
  'Sherif',     'Aya', 'Mostafa', 'Youssef',    'Ziad',    'Dina',    'Lina',
    'Reem',   'Fares',   'Retaj',   'Layla',  'Habiba',   'Malak',   'Salma',
   'Hamza',     'Ali',  'Hassan',   'Tarek',  'Bassel',   'Karim',  'Yassin',
    'Jana',   'Menna',    'Amir']
Length: 31, dtype: str

In [141]:
df["last_name"] = df["last_name"].str.strip().str.title()
df["last_name"].unique()

<StringArray>
[ 'Rashad',    'Zaki',  'Shafik',   'Osman',   'Nabil',   'Fahmy',   'Saleh',
   'Wahba',   'Fouad',  'Hegazy',   'Halim',    'Adel', 'Mansour', 'Ibrahim',
   'Sabry',   'Kamel',    'Riad',   'Gamal',    'Badr']
Length: 19, dtype: str

In [142]:
df["neighborhood"] = df["neighborhood"].str.strip().str.title()
df["neighborhood"].unique()

<StringArray>
['Heliopolis', 'Zamalek', 'Nasr City', 'Shubra', 'Maadi']
Length: 5, dtype: str

In [143]:
df["membership_status"] = df["membership_status"].str.strip().str.title()
df["membership_status"].unique()

<StringArray>
['Inactive', 'Active']
Length: 2, dtype: str

In [144]:
df["genre"] = df["genre"].str.strip().str.title()
df["genre"].unique()

<StringArray>
[        'Mystery',         'Science',      'Historical',          'Nature',
       'Adventure',          'Poetry',      'Friendship', 'Science Fiction']
Length: 8, dtype: str

In [145]:
df["publisher"] = df["publisher"].str.strip().str.title()
df["publisher"].unique()

<StringArray>
['Delta House', 'Oasis Books', 'Nile Press', 'Cairo Young Readers']
Length: 4, dtype: str

In [147]:
import sqlite3
conn = sqlite3.connect("library Database.db")

print ("members table from db")
members = pd.read_sql("SELECT * FROM members", conn)

# IDs الموجودة في جدول الـ members
registered_ids = set(members["member_id"])

# IDs الموجودة في الـ combined dataset
used_ids = set(df["member_id"].dropna())

# إيجاد الـ member_id الموجودة في الـ combined dataset
# ولكنها غير موجودة في جدول الأعضاء
invalid_ids = used_ids - registered_ids

print("Invalid member IDs:")
print(sorted(invalid_ids))

print("Number of invalid member IDs:", len(invalid_ids))

members table from db
Invalid member IDs:
[]
Number of invalid member IDs: 0

In [146]:
df.to_csv("Task2_cleaned_data.csv")